name: Node.js CI/CD

on:
  push:
    branches:
      - '**'  # Triggers on any push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on any pull request to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures all branches are available
        ref: ${{ github.ref }}  # Checks out the branch that triggered the workflow

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'

    - name: Print Directory Structure (Debugging)
      run: ls -R

    - name: Install dependencies
      run: npm install
      
    - name: Run Tests
      run: jest test
      working-directory: ./DevOpsOct2024Team6


    - name: Build Project
      run: npm run build
      working-directory: ./DevOpsOct2024Team6
