name: Node.js CI/CD

on:
  push:
    branches:
      - '**'  # Triggers on any push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on any pull request to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'

    - name: Print Directory Structure (Debugging)
      run: ls -R

    - name: Install dependencies
      run: npm install
      
    - name: Run Tests
      run: npm test  # Runs Jest using package.json settings

    # Discord Notification Step
    - name: Send Discord Notification
      if: always()  # notification is sent whether the workflow succeeds or fails
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Uses the stored secret
      run: |
        STATUS="Success"
        COLOR="3066993"
        if [ "${{ job.status }}" != "success" ]; then
          STATUS="Failed"
          COLOR="15158332"
        fi

        curl -H "Content-Type: application/json" -X POST -d "{
          \"username\": \"GitHub Actions\",
          \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
          \"embeds\": [{
            \"title\": \"GitHub CI/CD Build Status\",
            \"description\": \"Workflow *Node.js CI/CD* has **$STATUS** for repository **${{ github.repository }}**.\",
            \"color\": $COLOR,
            \"fields\": [
              {\"name\": \"Branch\", \"value\": \"${{ github.ref }}\", \"inline\": true},
              {\"name\": \"Commit\", \"value\": \"${{ github.sha }}\", \"inline\": true}
            ],
            \"footer\": {\"text\": \"GitHub Actions | ${{ github.event_name }}\", \"icon_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\"}
          }]
        }" "$DISCORD_WEBHOOK"
